# Generated by Django 5.2.4 on 2025-09-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="api_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_type",
            field=models.CharField(
                choices=[
                    ("single", "Single Room"),
                    ("double", "Double Room"),
                    ("deluxe", "Deluxe Room"),
                    ("Suit", "Suit Room"),
                    ("Family", "Family Room"),
                ],
                max_length=10,
            ),
        ),
    ]
