# Generated by Django 5.2.4 on 2025-09-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_hotel_api_id_alter_room_room_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="api_hotel_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_type",
            field=models.CharField(
                choices=[
                    ("single", "Single Room"),
                    ("double", "Double Room"),
                    ("deluxe", "Deluxe Room"),
                    ("suit", "Suit Room"),
                    ("family", "Family Room"),
                ],
                max_length=10,
            ),
        ),
    ]
