# Generated by Django 5.2.4 on 2025-09-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_room_api_hotel_id_alter_room_room_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotel",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
