# Generated by Django 5.2.4 on 2025-09-21 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_hotel_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_type",
            field=models.CharField(
                choices=[
                    ("single", "Single Room"),
                    ("double", "Double Room"),
                    ("deluxe", "Deluxe Room"),
                    ("suite", "Suite Room"),
                    ("family", "Family Room"),
                ],
                max_length=10,
            ),
        ),
    ]
